USE QLSV_3_3_12
-- Procedure
-- 2a
CREATE PROC sp_ThemMotLop @MaLop VARCHAR(10), @TenLop NVARCHAR(50)
AS
	BEGIN
		INSERT INTO LOP VALUES (@MaLop, @TenLop, 0)
	END

EXEC sp_ThemMotLop CNTT03, N'Công nghệ thông tin 03'
-- 2b
CREATE PROC sp_ThemMotSinhVien @MASV VARCHAR(10), @HOTEN NVARCHAR(50), @NGSINH DATE, @GIOITINH NVARCHAR(10), @QUEQUAN NVARCHAR(50), @MALOP VARCHAR(10)
AS
	BEGIN
		INSERT INTO SINHVIEN(MASV, HOTEN, NGSINH, GIOITINH, QUEQUAN, MALOP) VALUES (@MASV,@HOTEN,@NGSINH,@GIOITINH,@QUEQUAN,@MALOP)
	END

EXEC sp_ThemMotSinhVien 'SV011',N'Ngô Kim L','2003-10-15',N'Nam',N'Lâm Đồng','CNTT03'
-- 2c
CREATE PROC sp_CNSiSo @MaLop VARCHAR(10)
AS
	BEGIN
		UPDATE LOP
		SET SISO = 
		(	
			SELECT COUNT(*)
			FROM SINHVIEN
			WHERE MALOP = @MaLop
		)
		WHERE MALOP = @MaLop
	END
EXEC sp_CNSiSo 'CNTT03'
-- 2d
CREATE PROC sp_CongMotDiem @MaSV VARCHAR(10), @MaMH VARCHAR(10), @HocKy INT
AS
	BEGIN
		UPDATE KETQUA
		SET DIEMTHI = DIEMTHI + 1
		WHERE MASV = @MaSV AND MAMH = @MaMH AND HOCKY = @HocKy
	END
EXEC sp_CongMotDiem 'SV005','MH08',3
--2e
CREATE PROC sp_TTSV @MaSV VARCHAR(10)
AS
	BEGIN
		SELECT HOTEN, NGSINH, GIOITINH, TENLOP
		FROM SINHVIEN S, LOP L
		WHERE MASV = @MaSV AND S.MALOP = L.MALOP
	END
EXEC sp_TTSV 'SV001'
-- 2f
CREATE PROC sp_DTrBinh_XLoai_SV @MASV VARCHAR(10)
AS
	BEGIN
		DECLARE @DTB FLOAT
		SELECT @DTB = (SUM(DIEMTHI*SOTC) / SUM(SOTC))
		FROM KETQUA K, MONHOC M
		WHERE MASV = @MASV AND K.MAMH = M.MAMH
		
		SELECT @DTB N'Điểm trung bình', CASE	WHEN @DTB >= 8 THEN N'Giỏi'
							WHEN @DTB >= 7 THEN N'Khá'	
							WHEN @DTB >= 5 THEN N'Trung bình'
							ELSE N'Yếu'
							END N'Xếp loại'
	END
EXEC sp_DTrBinh_XLoai_SV 'SV002'
-- 2g
CREATE PROC sp_Xem_SV_Lop @MaLop VARCHAR(10)
AS
	BEGIN
		SELECT *
		FROM SINHVIEN S, LOP L
		WHERE L.MALOP = @MaLop AND L.MALOP = S.MALOP
	END
EXEC sp_Xem_SV_Lop 'CNTT01'
-- 2h
CREATE PROC sp_XEM_HK_MH @MAMH VARCHAR(10), @HOCKY INT
AS
	BEGIN
		SELECT COUNT(*)
		FROM KETQUA
		WHERE MAMH = @MAMH AND HOCKY = @HOCKY
	END
EXEC sp_XEM_HK_MH 'MH01',1
-- 2i
CREATE PROC sp_KiemTraTrangThaiMonHoc   @MASV VARCHAR(10), @MAMH VARCHAR(10), @HOCKY INT
AS
    BEGIN
		DECLARE @TRANGTHAI NVARCHAR(20)
        IF NOT EXISTS (SELECT * FROM KETQUA WHERE MASV = @MASV AND MAMH = @MAMH AND HOCKY = @HOCKY)
            SET @TRANGTHAI = N'chưa đăng ký'
        ELSE
            BEGIN
                DECLARE @DIEM FLOAT
                SELECT @DIEM = DIEMTHI 
                FROM KETQUA 
                WHERE MASV = @MASV AND MAMH = @MAMH AND HOCKY = @HOCKY
                IF @DIEM IS NULL
                    SET @TRANGTHAI = N'chưa có điểm'
                ELSE IF @DIEM >= 5
                    SET @TRANGTHAI = N'Đạt'
                ELSE
                    SET @TRANGTHAI = N'Không đạt'
            END
		SELECT @TRANGTHAI
    END
EXEC sp_KiemTraTrangThaiMonHoc 'SV001','MH01',1
-- 2j
CREATE PROC sp_KhenThuong   @MASV VARCHAR(10), @HOCKY INT
AS
    BEGIN
        DECLARE @DTB_HK FLOAT
        SELECT @DTB_HK = SUM(K.DIEMTHI * M.SOTC) / SUM(M.SOTC)
        FROM KETQUA K, MONHOC M
        WHERE K.MAMH = M.MAMH AND MASV = @MASV AND HOCKY = @HOCKY
        GROUP BY MASV

		DECLARE @KHENTHUONG NVARCHAR(20) = CASE WHEN @DTB_HK >=8 THEN N'Khen thưởng'
												ELSE N'Không khen thưởng'
												End
		SELECT @KHENTHUONG
    END
EXEC sp_KhenThuong 'SV001',1
-- Function
-- 3a
CREATE FUNCTION f_XemTC (@MAMH VARCHAR(10))
RETURNS INT
AS
	BEGIN
		RETURN(	SELECT SOTC
				FROM MONHOC
				WHERE MAMH = @MAMH )
	END
SELECT dbo.f_XEMTC('MH01')
-- 3b
CREATE FUNCTION f_XemDTB (@MaSV VARCHAR(10))
RETURNS INT
AS
	BEGIN
		RETURN (	SELECT DIEMTB
					FROM SINHVIEN
					WHERE @MASV = MASV)
	END
SELECT dbo.f_XemDTB('SV001')
-- 3c
CREATE FUNCTION f_XemSVHocMH (@MaMH VARCHAR(10), @HocKy INT)
RETURNS INT
AS
	BEGIN
		RETURN (	SELECT COUNT(*)
					FROM KETQUA
					WHERE @MaMH = MAMH AND @HocKy = HocKy )
	END
SELECT dbo.f_XemSVHocMH('MH01',1)
-- 3d
CREATE FUNCTION f_XemDiemThi (@MaSV VARCHAR(10), @MAMH VARCHAR(10), @HOCKY INT)
RETURNS DECIMAL(4, 2)
AS
	BEGIN
		RETURN (	SELECT DIEMTHI
					FROM KETQUA
					WHERE @MaSV = MASV AND @MAMH = MAMH AND @HOCKY = HOCKY)
	END
SELECT DBO.f_XemDiemThi('SV001','MH01',1)
-- 3e
CREATE FUNCTION f_SoTCDat (@MASV VARCHAR(10), @HOCKY INT)
RETURNS INT
AS
	BEGIN
		RETURN (	SELECT SUM(SOTC)
					FROM KETQUA K, MONHOC M
					WHERE K.MAMH = M.MAMH AND MASV = @MASV AND HOCKY=@HOCKY)
	END
SELECT DBO.f_SoTCDat('SV001',1)
-- 3f
CREATE FUNCTION f_XemDSSV(@MALOP VARCHAR(10))
RETURNS TABLE
AS
		RETURN (	SELECT MASV, HOTEN, NGSINH
					FROM SINHVIEN S, LOP L
					WHERE S.MALOP = L.MALOP AND L.MALOP = @MALOP)
SELECT * FROM f_XemDSSV('CNTT01')
-- 3g
CREATE FUNCTION f_DSSV_Duoi_5(@MAMH VARCHAR(10), @HOCKY INT)
RETURNS TABLE
AS
	RETURN (	SELECT S.MASV, HOTEN, NGSINH,TENLOP
				FROM KETQUA K, SINHVIEN S, LOP L
				WHERE K.MAMH = @MAMH AND HOCKY = @HOCKY AND K.MASV = S.MASV AND S.MALOP = L.MALOP AND DIEMTHI < 5)
SELECT * FROM f_DSSV_Duoi_5('MH01',1)
-- 3h
CREATE FUNCTION f_ChuaHoc_MH(@MAMH VARCHAR(10))
RETURNS TABLE
AS
	RETURN(		SELECT S.MASV, HOTEN, NGSINH
				FROM SINHVIEN S
				WHERE S.MASV NOT IN (	SELECT DISTINCT K.MASV
									FROM KETQUA	K
									WHERE MAMH = @MAMH ) )
SELECT * FROM f_ChuaHoc_MH('MH01')
-- 3i
CREATE FUNCTION f_SV_DiemChinhThuc (@MASV VARCHAR(10))
RETURNS TABLE
AS
	RETURN(		SELECT K.MAMH, TENMH, MAX(DIEMTHI) N'Điểm thi'
				FROM KETQUA K, MONHOC M
				WHERE @MASV = K.MASV AND K.MAMH = M.MAMH
				GROUP BY K.MAMH, TENMH )
SELECT * FROM f_SV_DiemChinhThuc('SV001')
-- Trigger
-- 1a
CREATE TRIGGER trg_CapNhatSiSo ON SINHVIEN
AFTER INSERT, UPDATE, DELETE
AS
    BEGIN
        UPDATE LOP
        SET SISO = (    SELECT COUNT(MASV) 
                        FROM SINHVIEN 
                        WHERE SINHVIEN.MALOP = LOP.MALOP)
        WHERE MALOP IN (SELECT MALOP FROM inserted)
           OR MALOP IN (SELECT MALOP FROM deleted)
    END

INSERT INTO SINHVIEN (MASV, HOTEN, NGSINH, GIOITINH, QUEQUAN, MALOP, DIEMTB, XEPLOAI) VALUES
('SV012', N'Nguyễn Văn A', '2004-01-15', N'Nam', N'Hà Nội', 'CNTT01', 8.5, N'Giỏi')
SELECT * FROM LOP
DELETE FROM SINHVIEN
WHERE MaSV = 'SV012'

-- 1b
CREATE TRIGGER trg_ToiDa5Mon ON KETQUA
AFTER INSERT, UPDATE
AS
    BEGIN
        IF EXISTS (
            SELECT MASV, HOCKY
            FROM KETQUA
            WHERE MASV IN (SELECT MASV FROM inserted)
            GROUP BY MASV, HOCKY
            HAVING COUNT(MAMH) > 5
        )
        BEGIN
            PRINT(N'Mỗi sinh viên chỉ được đăng ký tối đa 5 môn trong mỗi học kỳ.')
            ROLLBACK TRAN
        END
    END

INSERT INTO KETQUA VALUES ('SV001','MH03',1,9)
INSERT INTO KETQUA VALUES ('SV001','MH04',1,9)
INSERT INTO KETQUA VALUES ('SV001','MH05',1,9)
SELECT Count(*)
FROM KETQUA
WHERE MASV = 'SV001'
INSERT INTO KETQUA VALUES ('SV001','MH06',1,9)
DELETE FROM KETQUA
WHERE MaSV = 'SV001' AND MAMH = 'MH05'

-- 1c
CREATE TRIGGER trg_ToiDa10TinChiBatBuoc ON KETQUA
AFTER INSERT, UPDATE
AS
    BEGIN
        IF EXISTS (
            SELECT k.MASV, k.HOCKY
            FROM KETQUA k, MONHOC m
            WHERE k.MAMH = m.MAMH
              AND m.BATBUOC = 1 
              AND k.MASV IN (SELECT MASV FROM inserted)
            GROUP BY k.MASV, k.HOCKY
            HAVING SUM(m.SOTC) > 10
        )
        BEGIN
            PRINT(N'Sinh viên chỉ đăng ký tối đa 10 tín chỉ bắt buộc mỗi học kỳ.')
            ROLLBACK TRAN
        END
    END

INSERT INTO KETQUA VALUES ('SV002','MH02',1,9)
SELECT Sum(SOTC)
FROM KETQUA K, MONHOC M
WHERE MASV = 'SV002' AND K.MAMH = M.MAMH AND BATBUOC = 1
INSERT INTO KETQUA VALUES ('SV002','MH05',1,9)
DELETE FROM KETQUA
WHERE MaSV = 'SV002' AND MAMH = 'MH05'

-- 1d
CREATE TRIGGER trg_CapNhatDiemTB_XepLoai ON KETQUA
AFTER INSERT, UPDATE, DELETE
AS
	BEGIN
		UPDATE SINHVIEN
		SET DIEMTB = ( SELECT SUM (DIEMTHI * SOTC) / SUM(SOTC)
					   FROM KETQUA k, MONHOC m
					   WHERE k.MASV = SINHVIEN.MASV
						 AND k.MAMH = m.MAMH )
		WHERE MASV IN (SELECT MASV FROM inserted)
		   OR MASV IN (SELECT MASV FROM deleted)

		UPDATE SINHVIEN
		SET XEPLOAI = 
			CASE
				WHEN DIEMTB < 5 THEN N'Yếu'
				WHEN DIEMTB >= 5 AND DIEMTB < 7 THEN N'Trung bình'
				WHEN DIEMTB >= 7 AND DIEMTB < 8 THEN N'Khá'
				WHEN DIEMTB >= 8 THEN N'Giỏi'
			END
		WHERE MASV IN (SELECT MASV FROM inserted)
		   OR MASV IN (SELECT MASV FROM deleted)
	END

SELECT *
FROM SINHVIEN
WHERE MASV = 'SV003'
INSERT INTO KETQUA VALUES ('SV003','MH05',1,6)
DELETE FROM KETQUA
WHERE MaSV = 'SV003' AND MAMH = 'MH05'

--
SELECT * FROM LOP
SELECT * FROM SINHVIEN
SELECT * FROM KETQUA
SELECT * FROM MONHOC