USE QLTV_3_4_12
-- 2a
CREATE PROC sp_TTDocGia @MADG VARCHAR(10)
AS
	BEGIN
		SELECT TENDG, DIACHI
		FROM DOCGIA
		WHERE @MADG = MADG
	END
EXEC sp_TTDocGia 'DG001'
-- 2b 
CREATE PROC sp_TTSach @MASH VARCHAR(10)
AS
	BEGIN
		SELECT TENSH, TACGIA
		FROM SACH 
		WHERE MASH = @MASH
	END
EXEC sp_TTSach 'S001'
-- 2c
CREATE PROC sp_KTSLMuonSach @MADG VARCHAR(10)
AS
	BEGIN
		SELECT COUNT(*)
		FROM MUONSACH
		WHERE MADG = @MADG AND NGAYTRA IS NULL
	END
EXEC sp_KTSLMuonSach 'DG002'
-- 2d
CREATE PROC sp_KTAiMuon @MASH VARCHAR(10)
AS
	BEGIN
		SELECT TENDG
		FROM MUONSACH M, DOCGIA D
		WHERE M.MADG = D.MADG AND MASH = @MASH AND NGAYTRA IS NULL
	END
EXEC sp_KTAiMuon 'S001'
-- 2e
CREATE PROC sp_SoSachMuon @MADG VARCHAR(10), @NGAY DATE
AS
	BEGIN
		SELECT COUNT(*)
		FROM MUONSACH
		WHERE MADG = @MADG AND NGAYMUON = @NGAY
	END
EXEC sp_SoSachMuon 'DG001','2023-10-25'
-- 2f
CREATE PROC sp_NgayMuonGanNhat @MASH VARCHAR(10)
AS
	BEGIN
		SELECT MAX(NGAYMUON)
		FROM MUONSACH
		WHERE MASH = @MASH
	END
EXEC sp_NgayMuonGanNhat 'S001'
-- Function
-- 3a
CREATE FUNCTION f_XemTTDG (@MADG VARCHAR(10))
RETURNS NVARCHAR(300)
AS
	BEGIN
		DECLARE @TENDG NVARCHAR(100), @QUEQUAN NVARCHAR(200)
		SELECT @TENDG = TenDG, @QUEQUAN = DIACHI
		FROM DOCGIA
		WHERE MADG = @MADG
		RETURN @TENDG + N' có địa chỉ ở ' + @QueQuan
	END
SELECT DBO.f_XemTTDG('DG001')
-- 3b
CREATE FUNCTION f_DSDangMuon (@MADG VARCHAR(10))
RETURNS TABLE
AS
	RETURN (	SELECT S.MASH, TENSH
				FROM MUONSACH M, SACH S
				WHERE M.MASH = S.MASH AND MADG = @MADG)
SELECT * FROM DBO.f_DSDangMuon('DG001')
-- 3c
CREATE FUNCTION f_DSDGTungMuonSH (@MASH VARCHAR(10))
RETURNS TABLE
AS
		RETURN (	SELECT D.MADG, TENDG
					FROM DOCGIA D, MUONSACH M
					WHERE D.MADG = M.MADG AND MASH = @MASH)
SELECT * FROM DBO.f_DSDGTungMuonSH('S001')
-- 3d
CREATE FUNCTION f_SoSachMuonTrongThang (@MADG VARCHAR(10), @THANG INT)
RETURNS INT
AS
	BEGIN
		RETURN(	SELECT COUNT(*)
				FROM MUONSACH
				WHERE MADG = @MADG AND MONTH(NGAYMUON) = @THANG)
	END
SELECT DBO.f_SoSachMuonTrongThang('DG001',10)
-- Trigger
-- 1a
CREATE TRIGGER trg_KTTuoi ON DOCGIA
FOR INSERT, UPDATE
AS
	BEGIN
		IF EXISTS (	SELECT *
					FROM inserted
					WHERE YEAR(GETDATE()) - YEAR(NGAYSINH)  < 15 )
			BEGIN
				PRINT N'Độ tuổi phải lớn hơn hoặc bằng 15'
				ROLLBACK TRAN
			END
	END
INSERT INTO DOCGIA (MADG, TENDG, NGAYSINH, PHAI, DIACHI) VALUES
('DG012', N'Nguyễn Thanh Nam', '2026-05-10', N'Nam', N'TP. Hồ Chí Minh')
-- 1b
CREATE TRIGGER trg_KiemTraPhai ON DOCGIA
FOR INSERT, UPDATE
AS
    BEGIN
        IF EXISTS (
            SELECT * FROM inserted
            WHERE PHAI NOT IN (N'Nam', N'Nữ') )
			BEGIN
				PRINT(N'Phái của độc giả phải là Nam hoặc Nữ.')
				ROLLBACK TRAN
			END
    END
INSERT INTO DOCGIA (MADG, TENDG, NGAYSINH, PHAI, DIACHI) VALUES
('DG012', N'Nguyễn Thanh Nam', '2000-05-10', N'Hii', N'TP. Hồ Chí Minh')

-- 1c
CREATE TRIGGER trg_KiemTraLoaiSach ON SACH
AFTER INSERT, UPDATE
AS
    BEGIN
        IF EXISTS (
            SELECT * FROM inserted
            WHERE LOAI NOT IN (N'Khoa học tự nhiên', N'Xã hội', N'Kinh tế', N'Truyện')
        )
        BEGIN
            PRINT(N'Loại sách không hợp lệ.')
            ROLLBACK TRANSACTION
        END
    END
INSERT INTO SACH (MASH, TENSH, TACGIA, LOAI, TINHTRANG) VALUES
('S011', N'Nhà giả kim', N'Paulo Coelho', N'Comic', N'Chưa mượn')

-- 1d
CREATE TRIGGER trg_MuonSach ON MUONSACH
AFTER INSERT
AS
    BEGIN
        IF EXISTS (
            SELECT I.MADG
            FROM inserted I, MUONSACH M
            WHERE I.MADG = M.MADG AND M.NGAYTRA IS NULL
            GROUP BY I.MADG
            HAVING COUNT(M.MASH) > 3 
        )
			BEGIN
				PRINT(N'Độc giả đã mượn tối đa 3 cuốn sách chưa trả, không được mượn tiếp.')
				ROLLBACK TRANSACTION
			END
        ELSE
			BEGIN
				UPDATE SACH
				SET TINHTRANG = N'Đã mượn'
				WHERE MASH IN (SELECT MASH FROM inserted)
			END
    END
INSERT INTO MUONSACH (MADG, MASH, NGAYMUON, NGAYTRA) VALUES
('DG001', 'S006', '2023-10-25', NULL)
--
SELECT * FROM SACH
SELECT * FROM MUONSACH
SELECT * FROM DOCGIA