USE QLBH_3_5_12

-- Trigger
-- 1a
CREATE TRIGGER trg_CauA ON PHIEUNHAP
AFTER INSERT
AS
    BEGIN
        UPDATE PHIEUNHAP
        SET NGAYNHAP = GETDATE()
        WHERE MAPN IN (SELECT MAPN FROM inserted)
    END
INSERT INTO PHIEUNHAP(MAPN, MANCC) VALUES ('PN999', 'NCC01')
SELECT * FROM PHIEUNHAP WHERE MAPN = 'PN999'

-- 1b
CREATE TRIGGER trg_CauB ON HOADON
AFTER INSERT
AS
    BEGIN
        UPDATE HOADON
        SET NGAYBAN = GETDATE()
        WHERE MAHD IN (SELECT MAHD FROM inserted)
    END
INSERT INTO HOADON(MAHD, MAKH) VALUES ('HD999', 'KH001')
SELECT * FROM HOADON WHERE MAHD = 'HD999'

-- 1c
CREATE TRIGGER trg_CauC ON CHITIETPN
AFTER INSERT
AS
    BEGIN
        UPDATE CHITIETPN
        SET THANHTIEN = SOLUONG * GIANHAP
        WHERE MAPN IN (SELECT MAPN FROM inserted) AND MAHG IN (SELECT MAHG FROM inserted)

        UPDATE PHIEUNHAP
        SET TIENNHAP = (SELECT SUM(THANHTIEN) FROM CHITIETPN WHERE CHITIETPN.MAPN = PHIEUNHAP.MAPN)
        WHERE MAPN IN (SELECT MAPN FROM inserted)

        UPDATE HANG
        SET SOLUONGTON = ISNULL(SOLUONGTON, 0) + (SELECT SUM(SOLUONG) FROM inserted WHERE inserted.MAHG = HANG.MAHG)
        WHERE MAHG IN (SELECT MAHG FROM inserted)
    END

-- 1d
CREATE TRIGGER trg_CauD ON CHITIETHD
AFTER INSERT
AS
    BEGIN
        IF EXISTS (
            SELECT i.MAHG
            FROM inserted i, HANG h
            WHERE i.MAHG = h.MAHG AND h.SOLUONGTON < i.SOLUONG
        )
        BEGIN
            PRINT(N'Không đủ hàng để bán.')
            ROLLBACK TRANSACTION
            RETURN
        END

        UPDATE CHITIETHD
        SET GIABAN = (
            SELECT TOP 1 GIA 
            FROM DONGIA 
            WHERE DONGIA.MAHG = CHITIETHD.MAHG 
            ORDER BY NGAYCN DESC
        )
        WHERE MAHD IN (SELECT MAHD FROM inserted) AND MAHG IN (SELECT MAHG FROM inserted)

        UPDATE CHITIETHD
        SET THANHTIEN = SOLUONG * GIABAN
        WHERE MAHD IN (SELECT MAHD FROM inserted) AND MAHG IN (SELECT MAHG FROM inserted)

        UPDATE HOADON
        SET TIENBAN = (SELECT SUM(THANHTIEN) FROM CHITIETHD WHERE CHITIETHD.MAHD = HOADON.MAHD)
        WHERE MAHD IN (SELECT MAHD FROM inserted)

        UPDATE HANG
        SET SOLUONGTON = SOLUONGTON - (SELECT SUM(SOLUONG) FROM inserted WHERE inserted.MAHG = HANG.MAHG)
        WHERE MAHG IN (SELECT MAHG FROM inserted)

        UPDATE HANG
        SET TINHTRANG = N'Hết hàng'
        WHERE SOLUONGTON <= 0 AND MAHG IN (SELECT MAHG FROM inserted)

        UPDATE HOADON
        SET GIAMGIA = 
            CASE 
                WHEN TIENBAN < 200000 THEN '0'
                WHEN TIENBAN >= 200000 AND TIENBAN < 500000 THEN '5%'
                WHEN TIENBAN >= 500000 THEN '10%'
            END
        WHERE MAHD IN (SELECT MAHD FROM inserted)

        UPDATE HOADON
        SET THANHTOAN = 
            CASE 
                WHEN TIENBAN < 200000 THEN TIENBAN
                WHEN TIENBAN >= 200000 AND TIENBAN < 500000 THEN TIENBAN * 0.95
                WHEN TIENBAN >= 500000 THEN TIENBAN * 0.9
            END
        WHERE MAHD IN (SELECT MAHD FROM inserted)
    END

-- Procedure
-- 2a
CREATE PROC sp_DSHoaDonKH @MAKH VARCHAR(10)
AS
    BEGIN
        SELECT MAHD, NGAYBAN, TIENBAN, THANHTOAN
        FROM HOADON
        WHERE MAKH = @MAKH
    END
EXEC sp_DSHoaDonKH 'KH001'

-- 2b
CREATE PROC sp_ThongTinHoaDon @MAHD VARCHAR(10), @NGAYLAP DATE OUTPUT, @TRIGIA MONEY OUTPUT
AS
    BEGIN
        SELECT @NGAYLAP = NGAYBAN, @TRIGIA = THANHTOAN
        FROM HOADON
        WHERE MAHD = @MAHD
    END
DECLARE @Ngay DATE, @Gia MONEY
EXEC sp_ThongTinHoaDon 'HD001', @Ngay OUTPUT, @Gia OUTPUT
PRINT N'Ngày lập: ' + CONVERT(VARCHAR, @Ngay) + N' - Trị giá: ' + CONVERT(VARCHAR, @Gia)

-- 2c
CREATE PROC sp_ThongTinHang @MAHG VARCHAR(10), @TENHG NVARCHAR(50) OUTPUT, @SOLUONGTON INT OUTPUT, @TENNSX NVARCHAR(50) OUTPUT
AS
    BEGIN
        SELECT @TENHG = h.TENHG, @SOLUONGTON = h.SOLUONGTON, @TENNSX = n.TENNSX
        FROM HANG h, NHASX n
        WHERE h.MANSX = n.MANSX AND h.MAHG = @MAHG
    END
DECLARE @TenHang NVARCHAR(50), @SLTon INT, @TenNSX NVARCHAR(50)
EXEC sp_ThongTinHang 'HG001', @TenHang OUTPUT, @SLTon OUTPUT, @TenNSX OUTPUT
PRINT N'Tên hàng: ' + @TenHang + N' - Tồn: ' + CAST(@SLTon AS VARCHAR) + N' - NSX: ' + @TenNSX

-- 2d
CREATE PROC sp_DSHangCuaNSX @MANSX VARCHAR(10)
AS
    BEGIN
        SELECT MAHG, TENHG, DVT
        FROM HANG
        WHERE MANSX = @MANSX
    END
EXEC sp_DSHangCuaNSX 'NSX01'

-- 2e
CREATE PROC sp_KhachHangCuaHD @MAHD VARCHAR(10), @TENKH NVARCHAR(50) OUTPUT, @DCHI NVARCHAR(100) OUTPUT, @DTHOAI VARCHAR(15) OUTPUT
AS
    BEGIN
        SELECT @TENKH = k.TENKH, @DCHI = k.DCHI, @DTHOAI = k.DTHOAI
        FROM KHACHHG k, HOADON h
        WHERE k.MAKH = h.MAKH AND h.MAHD = @MAHD
    END
DECLARE @TenKH NVARCHAR(50), @DiaChi NVARCHAR(100), @SDT VARCHAR(15)
EXEC sp_KhachHangCuaHD 'HD001', @TenKH OUTPUT, @DiaChi OUTPUT, @SDT OUTPUT
PRINT N'Khách hàng: ' + @TenKH + N' - Địa chỉ: ' + @DiaChi + N' - ĐT: ' + @SDT

-- 2f
CREATE PROC sp_PhanLoaiKhachHang @MAKH VARCHAR(10), @LOAIKH NVARCHAR(30) OUTPUT
AS
    BEGIN
        DECLARE @DOANHSO MONEY
        SELECT @DOANHSO = SUM(THANHTOAN)
        FROM HOADON
        WHERE MAKH = @MAKH

        IF @DOANHSO >= 10000000
            SET @LOAIKH = N'VIP'
        ELSE IF @DOANHSO >= 6000000 AND @DOANHSO < 10000000
            SET @LOAIKH = N'KH thành viên'
        ELSE
            SET @LOAIKH = N'KH thân thiết'
    END
DECLARE @Loai NVARCHAR(30)
EXEC sp_PhanLoaiKhachHang 'KH001', @Loai OUTPUT
PRINT N'Phân loại: ' + @Loai

-- 2g
CREATE PROC sp_DonGiaMoiNhat @MAHG VARCHAR(10), @GIAMOINHAT MONEY OUTPUT
AS
    BEGIN
        SELECT TOP 1 @GIAMOINHAT = GIA
        FROM DONGIA
        WHERE MAHG = @MAHG
        ORDER BY NGAYCN DESC
    END
DECLARE @GiaMoi MONEY
EXEC sp_DonGiaMoiNhat 'HG001', @GiaMoi OUTPUT
PRINT N'Giá mới nhất: ' + CONVERT(VARCHAR, @GiaMoi)

-- Function
-- 3a
CREATE FUNCTION fn_SoLuongHD (@MAKH VARCHAR(10)) RETURNS INT
AS
    BEGIN
        DECLARE @SL INT
        SELECT @SL = COUNT(MAHD) 
        FROM HOADON 
        WHERE MAKH = @MAKH
        RETURN ISNULL(@SL, 0)
    END
SELECT dbo.fn_SoLuongHD('KH001') AS 'SoLuongHoaDon'

-- 3b
CREATE FUNCTION fn_TriGiaHD (@MAHD VARCHAR(10)) RETURNS MONEY
AS
    BEGIN
        DECLARE @TRIGIA MONEY
        SELECT @TRIGIA = THANHTOAN 
        FROM HOADON 
        WHERE MAHD = @MAHD
        RETURN ISNULL(@TRIGIA, 0)
    END
SELECT dbo.fn_TriGiaHD('HD001') AS 'TriGiaHD'

-- 3c
CREATE FUNCTION fn_TongSLBan (@MAHG VARCHAR(10), @NGAYBAN DATE) RETURNS INT
AS
    BEGIN
        DECLARE @TONG INT
        SELECT @TONG = SUM(c.SOLUONG)
        FROM CHITIETHD c, HOADON h
        WHERE c.MAHD = h.MAHD AND c.MAHG = @MAHG AND h.NGAYBAN = @NGAYBAN
        RETURN ISNULL(@TONG, 0)
    END
SELECT dbo.fn_TongSLBan('HG001', '2025-09-11') AS 'TongSLBan'

-- 3d
CREATE FUNCTION fn_DoanhSoKH (@MAKH VARCHAR(10)) RETURNS MONEY
AS
    BEGIN
        DECLARE @DS MONEY
        SELECT @DS = SUM(THANHTOAN) 
        FROM HOADON 
        WHERE MAKH = @MAKH
        RETURN ISNULL(@DS, 0)
    END
SELECT dbo.fn_DoanhSoKH('KH001') AS 'DoanhSo'

-- 3e
CREATE FUNCTION fn_DSHangNhapTuNCC (@MANCC VARCHAR(10)) RETURNS TABLE
AS
    RETURN (
        SELECT h.MAHG, h.TENHG, SUM(c.SOLUONG) AS TONGSL
        FROM HANG h, CHITIETPN c, PHIEUNHAP p
        WHERE h.MAHG = c.MAHG AND c.MAPN = p.MAPN AND p.MANCC = @MANCC
        GROUP BY h.MAHG, h.TENHG
    )
SELECT * FROM dbo.fn_DSHangNhapTuNCC('NCC01')

-- 3f
CREATE FUNCTION fn_ChiTietHoaDonBan (@MAHD VARCHAR(10)) RETURNS TABLE
AS
    RETURN (
        SELECT h.MAHG, h.TENHG, c.SOLUONG, c.GIABAN, c.THANHTIEN
        FROM HANG h, CHITIETHD c
        WHERE h.MAHG = c.MAHG AND c.MAHD = @MAHD
    )
SELECT * FROM dbo.fn_ChiTietHoaDonBan('HD001')

-- 3g
CREATE FUNCTION fn_ThongKeHangHoa (@MAHG VARCHAR(10)) RETURNS TABLE
AS
    RETURN (
        SELECT h.MAHG, h.TENHG, 
               ISNULL((SELECT SUM(SOLUONG) FROM CHITIETPN WHERE MAHG = h.MAHG), 0) AS SL_NHAP,
               ISNULL((SELECT SUM(SOLUONG) FROM CHITIETHD WHERE MAHG = h.MAHG), 0) AS SL_XUAT,
               h.SOLUONGTON AS SL_CONLAI
        FROM HANG h
        WHERE h.MAHG = @MAHG
    )
SELECT * FROM dbo.fn_ThongKeHangHoa('HG001')

-- Cursor
-- 4a
CREATE PROC sp_CauA 
AS
	BEGIN
		DECLARE @MAKH VARCHAR(10), @TenKH NVARCHAR(50), @DoanhThu MONEY
		DECLARE cur_CauA cursor for (	SELECT K.MAKH, TENKH, SUM(THANHTOAN)
										FROM KHACHHG K, HOADON H
										WHERE K.MAKH = H.MAKH
										GROUP BY K.MAKH, TENKH	)
		OPEN cur_CauA
		PRINT N'Mã khách hàng' + SPACE(10) + N'Tên khách hàng' + SPACE(50) + N'Doanh thu'
		FETCH NEXT FROM cur_CauA into @MAKH, @TENKH, @DOANHTHU
		WHILE(@@FETCH_STATUS = 0)
			BEGIN
				PRINT @MAKH + SPACE(10) + @TenKH + SPACE(50) + CONVERT(VARCHAR(20), ISNULL(@DoanhThu,0))
				FETCH NEXT FROM cur_CauA into @MAKH, @TENKH, @DOANHTHU
			END
        CLOSE cur_CauA
		DEALLOCATE cur_CauA
	END
EXEC sp_CauA

-- 4b
CREATE PROC sp_CauB @TuNgay DATE, @DenNgay DATE
AS
	BEGIN
	    DECLARE cur_TKHang CURSOR FOR
        SELECT MAHG, TENHG FROM HANG
            
        DECLARE @MAHG_C VARCHAR(10), @TENHG_C NVARCHAR(50)
        DECLARE @TONGNHAP INT, @TONGBAN INT
        
        OPEN cur_TKHang
        FETCH NEXT FROM cur_TKHang INTO @MAHG_C, @TENHG_C
        WHILE (@@FETCH_STATUS = 0)
        BEGIN
            SELECT @TONGNHAP = ISNULL(SUM(c.SOLUONG), 0)
            FROM CHITIETPN c, PHIEUNHAP p
            WHERE c.MAPN = p.MAPN AND c.MAHG = @MAHG_C AND p.NGAYNHAP BETWEEN @TuNgay AND @DenNgay
            
            SELECT @TONGBAN = ISNULL(SUM(c.SOLUONG), 0)
            FROM CHITIETHD c, HOADON h
            WHERE c.MAHD = h.MAHD AND c.MAHG = @MAHG_C AND h.NGAYBAN BETWEEN @TuNgay AND @DenNgay
            
            PRINT N'Mã hàng: ' + @MAHG_C + N', Tên: ' + @TENHG_C + N', Tổng nhập: ' + CONVERT(NVARCHAR(10),@TONGNHAP) + N', Tổng bán: ' + CONVERT(NVARCHAR(10),@TONGBAN)
            
            FETCH NEXT FROM cur_TKHang INTO @MAHG_C, @TENHG_C
        END
        CLOSE cur_TKHang
        DEALLOCATE cur_TKHang
	END
EXEC sp_CauB '2025-09-01','2025-09-17'

-- 4c
CREATE PROC sp_CauC @MAHD VARCHAR(10)
AS
	BEGIN
		DECLARE @MAHG VARCHAR(10), @TENHG NVARCHAR(50), @SLBan INT, @GiaBan MONEY, @ThanhTien MONEY
		DECLARE cur_CauC cursor for (	SELECT H.MAHG, TENHG, SOLUONG, GIA, (SOLUONG * GIA)
										FROM CHITIETHD C, HANG H, DONGIA D
										WHERE C.MAHD = @MAHD 
											AND C.MAHG = H.MAHG AND H.MAHG = D.MAHG )
		OPEN cur_CauC
		PRINT N'Mã hàng' + Space(10) + N'Tên hàng' + Space(50) + N'số lượng' + Space(10) + N'Giá bán' + Space(20) + N'Thành tiền'
		FETCH NEXT FROM cur_CauC into @MAHG, @TENHG, @SLBAN, @GIABAN, @THANHTIEN
		WHILE(@@FETCH_STATUS = 0)
			BEGIN
				PRINT @MAHG + Space(10) + @TENHG + Space(50) + CONVERT(NVARCHAR(10),@SLBAN) + Space(10) + CONVERT(NVARCHAR(20),@GIABAN) + Space(20) + CONVERT(NVARCHAR(20),@THANHTIEN)
				FETCH NEXT FROM cur_CauC into @MAHG, @TENHG, @SLBAN, @GIABAN, @THANHTIEN
			END
		CLOSE cur_CauC
		DEALLOCATE cur_CauC
	END
EXEC sp_CauC 'HD001'